---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ buildkite_agent_name }}"

- name: Manage Homebrew
  import_tasks: homebrew.yml

- name: Manage Macports
  import_tasks: macports.yml

- name: Install fail2ban
  become: true
  community.general.macports:
    name: fail2ban
    state: present

- name: Ensure fail2ban is started
  become: true
  command: /opt/local/bin/port load fail2ban

- name: Create git mirrors directory
  file:
    path: /usr/local/etc/buildkite-agent/git-mirrors
    state: directory

- name: Setup agent environment hook
  no_log: true
  template:
    src: buildkite-agent-hook-environment.sh
    dest: /usr/local/etc/buildkite-agent/hooks/environment

- name: Configure buildkite-agent
  template:
    src: buildkite-agent.cfg.j2
    dest: /usr/local/etc/buildkite-agent/buildkite-agent.cfg
  notify:
    - restart-buildkite
