---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ buildkite_agent_name }}"
  when: is_static

- name: Install Packages
  import_tasks: packages.yml

- name: Virtualization/Docker
  import_tasks: virt.yml

- name: Misc
  import_tasks: misc.yml

- name: Buildkite Agent
  import_tasks: buildkite-agent.yml
