---
- set_fact:
    container_registry_username: "{{ lookup('hashi_vault', 'secret=secret/kibana-issues/dev/container-registry:username') }}"
    container_registry_password: "{{ lookup('hashi_vault', 'secret=secret/kibana-issues/dev/container-registry:password') }}"
  no_log: true

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ buildkite_agent_name }}"
  when: is_static and not is_docker

- name: Install Packages
  import_tasks: packages.yml

- name: Virtualization/Docker
  import_tasks: virt.yml

- name: Misc
  import_tasks: misc.yml

- name: Buildkite Agent
  import_tasks: buildkite-agent.yml

- name: Elastic Agent
  import_tasks: elastic-agent.yml
