---
- hosts: prod
  user: "{{default_username}}"
  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.mac.homebrew
    - common
    - role: elastic-agent
      when: ansible_machine != "arm64"
