- hosts: prod
  vars_files:
    - group_vars/all.yml
  user: "{{default_username}}"
  tasks:
    - name: Restart buildkite-agent
      shell: /usr/local/bin/brew services restart buildkite/buildkite/buildkite-agent
