---
- name: Install Elastic Agent
  become: true
  shell:
    creates: /Library/Elastic/Agent
    cmd: |
      rm -rf elastic-agent-7.14.1-darwin-x86_64*
      curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.14.1-darwin-x86_64.tar.gz
      tar xzvf elastic-agent-7.14.1-darwin-x86_64.tar.gz
      cd elastic-agent-7.14.1-darwin-x86_64
      ./elastic-agent install -f

- name: Configure Elastic Agent
  become: true
  template:
    src: elastic-agent.yml.j2
    dest: /Library/Elastic/Agent/elastic-agent.yml
  notify:
    - restart-elastic-agent
