---
- name: Install Elastic Agent
  become: true
  args:
    executable: /bin/bash
  shell:
    cmd: |
      if [[ ! -d /opt/elastic-agent-install ]]; then
        cd /opt
        curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.17.0-linux-x86_64.tar.gz
        tar xzf elastic-agent-7.17.0-linux-x86_64.tar.gz
        mv elastic-agent-7.17.0-linux-x86_64 /opt/elastic-agent-install
        cd /opt/elastic-agent-install
        ./elastic-agent install -f
      fi

- name: Configure Elastic Agent
  become: true
  template:
    src: elastic-agent.yml.j2
    dest: /opt/elastic-agent-install/elastic-agent.yml
  notify:
    - restart-elastic-agent

- name: Create role id file
  copy:
    dest: "/var/lib/buildkite-agent/.vault-role-id"
    content: "{{ lookup('hashi_vault', 'secret=secret/kibana-issues/dev/buildkite-vault-credentials:role_id') }}"
    mode: "0600"
    owner: "buildkite-agent"

- name: Create secret id file
  copy:
    dest: "/var/lib/buildkite-agent/.vault-secret-id"
    content: "{{ lookup('hashi_vault', 'secret=secret/kibana-issues/dev/buildkite-vault-credentials:secret_id') }}"
    mode: "0600"
    owner: "buildkite-agent"
